<?php

namespace CBCMapBundle\Repository;

/**
 * CBCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CBCRepository extends \Doctrine\ORM\EntityRepository
{
}
